# Generated by Django 5.1.6 on 2025-03-02 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomtype_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
